"""second  migrations

Revision ID: 51ae781bded8
Revises: 85c69a727b4d
Create Date: 2024-05-27 11:48:13.539104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51ae781bded8'
down_revision = '85c69a727b4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enseignant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('grade', sa.String(length=200), nullable=False),
    sa.Column('specialite', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filiere_id', sa.Integer(), nullable=True),
    sa.Column('annee_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['annee_id'], ['annee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filiere_id'], ['filiere.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('etudiant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filiere_id', sa.Integer(), nullable=True),
    sa.Column('annee_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['annee_id'], ['annee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filiere_id'], ['filiere.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.drop_table('etudiants')
    op.drop_table('enseignants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enseignants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('matricule', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('specialite', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filiere_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['annee_id'], ['annee.id'], name='enseignants_annee_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filiere_id'], ['filiere.id'], name='enseignants_filiere_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateur.id'], name='enseignants_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='enseignants_pkey'),
    sa.UniqueConstraint('matricule', name='enseignants_matricule_key')
    )
    op.create_table('etudiants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('matricule', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filiere_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['annee_id'], ['annee.id'], name='etudiants_annee_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filiere_id'], ['filiere.id'], name='etudiants_filiere_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateur.id'], name='etudiants_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='etudiants_pkey'),
    sa.UniqueConstraint('matricule', name='etudiants_matricule_key')
    )
    op.drop_table('etudiant')
    op.drop_table('enseignant')
    # ### end Alembic commands ###
